### ISSUE TITLE
Support for biber

### ISSUE THREAD

**Issue by shiblon** [shiblon/latex-makefile#126] opened 2016-02-24 17:45 UTC
Originally reported on Google Code with ID 113

```
Biber is a UTF-8 able replacement for Bibtex for use with package biblatex.  The current
system for handling bibliographies doesn't work with the combination of these two,
since if biblatex is supplied option backend=biber, it stops writing bibliography information
to .aux and instead writes it to a .bcf file.

http://biblatex-biber.sourceforge.net/
http://www.ctan.org/tex-archive/help/Catalogue/entries/biblatex.html

It will need more thinking than I've done to solve the issue (ie. let bibtex and biber
coexist), but I provide my dirty hack as a starting point.  First of all

-----
BIBTEX := biber
-----

and then in the rule for creating .d, after the get-bibs line:

-----
if [ -n $*.bcf ]; then \
    grep datasource $*.bcf | sed -e 's/^[^>]*>//g' \
        -e 's/<.*$$//g' -e '/\.bib$$/!s/$$/.bib/' \
        -e 's!^!$(addprefix $*.,bbl aux aux.make): !' >> $*.d; \
fi; \
-----

This solves the simple case and allows me to return to writing my thesis ;)
I can provide more info / files if needed.
```

Reported by `jaripekka.juhala` on 2011-02-10 19:49:57

**Comment by llbit** [comment] 2018-11-23 16:00
I am also using biber, with the Makefile additions suggested above. This seems to work fine for my thesis.

Biber version 2.7.

I use XeLaTeX:
BUILD_STRATEGY := xelatex
BIBTEX := biber

```
XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017/Debian)
```


Makefile version: 2.2.1-alpha10

Here is the diff:


```diff
diff --git a/Makefile b/Makefile
index ea4dc52..ad0edc9 100644
--- a/Makefile
+++ b/Makefile
@@ -3334,6 +3334,11 @@ endif
        $(call get-graphics,$*) >> $*.d; \
        $(call get-log-index,$*,$(addprefix $*.,aux aux.make)) >> $*.d; \
        $(call get-bibs,$*.aux.make,$(addprefix $*.,bbl aux aux.make)) >> $*.d; \
+if [ -s $*.bcf ]; then \
+    grep datasource $*.bcf | sed -e 's/^[^>]*>//g' \
+        -e 's/<.*$$//g' -e '/\.bib$$/!s/$$/.bib/' \
+        -e 's!^!$(addprefix $*.,bbl aux aux.make): !' >> $*.d; \
+fi; \
        $(EGREP) -q "# MISSING stem" $*.d && $(SLEEP) 1 && $(RM) $*.pdf; \
        $(EGREP) -q "# MISSING format" $*.d && $(RM) $*.pdf; \
        $(call move-if-exists,$*.$(build_target_extension),$*.$(build_target_extension).1st.make); \
```

And `Makefile.ini`:

```
BUILD_STRATEGY := xelatex
BIBTEX := biber
```

**Comment by shiblon** [comment] 2018-11-28 18:04
Hey, @llbit , thanks for the update! I altered the sed a bit (removing the need for grep), moved it into its own file, and used the sed inclusion mechanism to pull it into the makefile under get-bcf-bibs. Please take a look at commit ef16cd4cd4c902fd35d8d0096b1285c33d2046ee, run the ./build script, and se if the resulting Makefile does what it is supposed to do.

**Comment by llbit** [comment] 2019-02-02 15:39
@shiblon I tried your changes but unfortunately the bibliographies disappear when I rebuild with the Makefile from commit ef16cd4cd4c902fd35d8d0096b1285c33d2046ee.

I have all my TeX code in this repository if you want to try reproducing the issue: https://github.com/llbit/joqvist-thesis

I build my thesis with this command: `make clean; make thesis`. When I build it with my edited Makefile I get 205 pages, when I build with your updated version I get 193 pages because the bibliographies are missing.

**Comment by shiblon** [comment] 2019-02-20 00:44
That seems pretty odd. Is it just not running latex enough times, perhaps?
I'll take a look and see if I can make it happen over here.

I wonder what the difference is between the changes I made and the changes
you suggested. As I recall, they were pretty similar...

**Comment by k4rtik** [comment] 2020-11-25 16:12
@llbit your patch shown in https://github.com/shiblon/latex-makefile/issues/126#issuecomment-441275351 works for me with the default build strategy. Thanks for sharing.

**Comment by shiblon** [comment] 2020-12-08 20:14
OK, it looks like what happened is the Makefile wasn't regenerated in commit  ef16cd4 (in fact, the generated Makefile isn't in the source repo).

Did you try regenerating on commit  ef16cd4? That should have done the trick. Running the `./build` script from the repo root should get you there.

It's probably a good idea for me to put the generated Makefile into the repo, though, so I'm committing that change now. Try the `Makefile` from commit  d4770f94a4bf5cee1323094b8a6d92bcbe3aa5d6.

**Comment by k4rtik** [comment] 2020-12-10 12:54
I am sure I had to build the `Makefile` on first time use. I tried the Makefile you committed and it gives me the following output with a suspicious `sed` error:
```
$ make
NOTE: You may ignore warnings about the following files:

     main.d

Makefile:2894: main.d: No such file or directory
= main.tex --> main.d main.pdf.1st.make (0-1) =
sed: can't read main: No such file or directory
= main.tex --> main.pdf (1-2) =
= main.tex --> main.pdf (1-3) =
= main.tex --> main.pdf (1-4) =
= main.tex --> main.pdf (1-5) =
LaTeX Warning: Citation 'sup19' on page 2 undefined on input line 193.
[...]
LaTeX Warning: Citation 'qhtt20' on page 26 undefined on input line 706.

LaTeX Warning: Empty bibliography on input line 711.

Underfull \vbox (badness 5832) has occurred while \output is active []

LaTeX Warning: There were undefined references.

Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                main
(biblatex)                and rerun LaTeX afterwards.

Success!  Wrote 30 pages, 288102 bytes to main.pdf
```

I am on macOS if it helps. The only difference in the two makefiles is the following:
```
-if [ -s $*.bcf ]; then \
-    grep datasource $*.bcf | sed -e 's/^[^>]*>//g' \
-        -e 's/<.*$$//g' -e '/\.bib$$/!s/$$/.bib/' \
-        -e 's!^!$(addprefix $*.,bbl aux aux.make): !' >> $*.d; \
-fi; \
+       $(call get-bcf-bibs,$*,$(addprefix $*.,bbl aux aux.make)) >> $*.d; \
```

I get a clean build after reverting your change to the previous version:
```
$ make
NOTE: You may ignore warnings about the following files:

     main.d

Makefile:2894: main.d: No such file or directory
= main.tex --> main.d main.pdf.1st.make (0-1) =
= references.bib main.aux --> main.bbl =
= main.tex --> main.pdf (1-2) =
= main.tex --> main.pdf (1-3) =
Underfull \vbox (badness 10000) has occurred while \output is active []
[...]
Underfull \vbox (badness 10000) has occurred while \output is active []

Success!  Wrote 33 pages, 320484 bytes to main.pdf
```

**Comment by shiblon** [comment] 2020-12-10 15:34
Question, when you say "previous version", does that mean there is a version that works, but that I broke it recently?

Can you help me know which version that would be?

**Comment by shiblon** [comment] 2020-12-10 15:40
@k4rtik , I have committed  dcf476152a5e46b5a14f59c37b448af17be29e39 which might help - can you give it a try and see if it fixes anything? I don't foresee it making a difference, but it might. If you also happen to have that "previous version" that works, let me know and we'll figure this out.

**Comment by k4rtik** [comment] 2020-12-10 16:28
Sorry, I realize how calling the version I had "previous" could be confusing. I was referring to the stable Makefile generated from your repo + @llbit's patch applied as I mentioned in https://github.com/shiblon/latex-makefile/issues/126#issuecomment-733803367.

I tried your new commit on the `bcf` branch but it does not change the error. `sed` still complains that it can't read `main` and no `.bbl` file is generated.

**Comment by shiblon** [comment] 2020-12-11 13:04
Can you post a full error please?

**Comment by k4rtik** [comment] 2020-12-11 13:08
Here:

```
$ make clean
$ ls
Makefile       Variables.ini  cointoss.qh    eptcs.cls      htt.ott.tex    main.tex       references.bib teleport2.qh
Targets.ini    bell00.qh      deutsch.qh     htt.ott        listproc.sty   ottalt.sty     teleport.qh
$ make
NOTE: You may ignore warnings about the following files:

     main.d

Makefile:2896: main.d: No such file or directory
= main.tex --> main.d main.pdf.1st.make (0-1) =
sed: can't read main: No such file or directory
= main.tex --> main.pdf (1-2) =
= main.tex --> main.pdf (1-3) =
= main.tex --> main.pdf (1-4) =
= main.tex --> main.pdf (1-5) =
LaTeX Warning: Citation 'supremacy19' on page 2 undefined on input line 193.

LaTeX Warning: Citation 'Preskill2012' on page 2 undefined on input line 193.

LaTeX Warning: Citation 'qsharp2018' on page 2 undefined on input line 193.

LaTeX Warning: Citation 'quipper2013' on page 2 undefined on input line 193.

LaTeX Warning: Citation 'scaffold12' on page 2 undefined on input line 193.

LaTeX Warning: Citation 'silq20' on page 2 undefined on input line 193.

LaTeX Warning: Citation 'Li2020' on page 3 undefined on input line 197.

LaTeX Warning: Citation 'huang2019' on page 3 undefined on input line 197.

LaTeX Warning: Citation 'qwire2017' on page 3 undefined on input line 203.

LaTeX Warning: Citation 'paykin2018' on page 3 undefined on input line 203.

LaTeX Warning: Citation 'silq20' on page 3 undefined on input line 203.

LaTeX Warning: Citation 'huang2019' on page 3 undefined on input line 203.

LaTeX Warning: Citation 'qdb2018' on page 3 undefined on input line 203.

LaTeX Warning: Citation 'aqhl2019' on page 3 undefined on input line 205.

LaTeX Warning: Citation 'floydhoare2012' on page 3 undefined on input line 205.

LaTeX Warning: Citation 'unruh2019' on page 3 undefined on input line 205.

LaTeX Warning: Citation 'wpe2016' on page 3 undefined on input line 205.

Underfull \vbox (badness 10000) has occurred while \output is active []

LaTeX Warning: Citation 'nanevski2008' on page 4 undefined on input line 207.

LaTeX Warning: Citation 'unruh2019' on page 4 undefined on input line 209.

LaTeX Warning: Citation 'dhondt2006' on page 4 undefined on input line 211.

LaTeX Warning: Citation 'dhondt2006' on page 4 undefined on input line 211.

LaTeX Warning: Citation 'floydhoare2012' on page 4 undefined on input line 211.

LaTeX Warning: Citation 'floydhoare2012' on page 4 undefined on input line 211.

LaTeX Warning: Citation 'hoare1969' on page 4 undefined on input line 211.

LaTeX Warning: Citation 'dijkstra1976' on page 4 undefined on input line 211.

LaTeX Warning: Citation 'gries1981' on page 4 undefined on input line 211.

Overfull \hbox (14.73712pt too wide) in paragraph at lines 211--212
\T1/ptm/m/n/10.95 grams such as [] [[]] and [] [[]] in the spirit of [],
 []

LaTeX Warning: Citation 'hoare1969' on page 4 undefined on input line 221.

LaTeX Warning: Citation 'floyd67' on page 4 undefined on input line 221.

Underfull \vbox (badness 10000) has occurred while \output is active []

LaTeX Warning: Citation 'nanevski2008' on page 6 undefined on input line 285.

LaTeX Warning: Citation 'moggi89' on page 7 undefined on input line 289.

LaTeX Warning: Citation 'perconti2012' on page 7 undefined on input line 289.

LaTeX Warning: Citation 'z32008' on page 7 undefined on input line 291.

LaTeX Warning: Citation 'coq2020' on page 7 undefined on input line 291.

LaTeX Warning: Citation 'fstar' on page 7 undefined on input line 297.

LaTeX Warning: Citation 'nielsen2010' on page 8 undefined on input line 382.

LaTeX Warning: Citation 'matuschak2019' on page 8 undefined on input line 382.

LaTeX Warning: Citation 'reynolds2002' on page 8 undefined on input line 386.

LaTeX Warning: Citation 'aqhl2019' on page 8 undefined on input line 386.

LaTeX Warning: Citation 'floydhoare2012' on page 8 undefined on input line 386.

LaTeX Warning: Citation 'wpe2016' on page 8 undefined on input line 386.

LaTeX Warning: Citation 'unruh2019' on page 8 undefined on input line 386.

LaTeX Warning: Citation 'unruh2019' on page 8 undefined on input line 386.

LaTeX Warning: Citation 'logicqm36' on page 9 undefined on input line 402.

LaTeX Warning: Citation 'qio' on page 11 undefined on input line 452.

LaTeX Warning: Citation 'qio' on page 11 undefined on input line 452.

LaTeX Warning: Citation 'unruh2019' on page 13 undefined on input line 499.

LaTeX Warning: Citation 'unruh2019' on page 14 undefined on input line 521.

Underfull \vbox (badness 1642) has occurred while \output is active []

Underfull \vbox (badness 10000) has occurred while \output is active []

LaTeX Warning: Citation 'dunfield2019bidirectional' on page 23 undefined on inp
ut line 668.

LaTeX Warning: Citation 'nanevski2008' on page 23 undefined on input line 668.

LaTeX Warning: Citation 'abspr07' on page 23 undefined on input line 668.

Overfull \hbox (89.53943pt too wide) in paragraph at lines 668--669
[]\T1/ptm/m/n/10.95 We would like to men-tion that the type sys-tem pre-sented
in this doc-u-ment is not bidi-rec-tional [[]]
 []

LaTeX Warning: Citation 'unruh2019' on page 25 undefined on input line 689.

LaTeX Warning: Citation 'qio' on page 25 undefined on input line 693.

LaTeX Warning: Citation 'ynot2008' on page 25 undefined on input line 695.

LaTeX Warning: Citation 'cross2017' on page 25 undefined on input line 695.

LaTeX Warning: Citation 'selinger2020' on page 25 undefined on input line 697.

LaTeX Warning: Citation 'fu2020linear' on page 25 undefined on input line 697.

LaTeX Warning: Citation 'so-arrows' on page 26 undefined on input line 699.

LaTeX Warning: Citation 'JorrandPerdrix2009' on page 26 undefined on input line
 701.

LaTeX Warning: Citation 'rssl2019' on page 26 undefined on input line 701.

LaTeX Warning: Citation 'rssl20' on page 26 undefined on input line 701.

LaTeX Warning: Citation 'rssl20' on page 26 undefined on input line 701.

LaTeX Warning: Citation 'rssl20' on page 26 undefined on input line 701.

LaTeX Warning: Citation 'dm4free2017' on page 26 undefined on input line 703.

LaTeX Warning: Citation 'qhtt20' on page 26 undefined on input line 706.

LaTeX Warning: Empty bibliography on input line 711.

Underfull \vbox (badness 5832) has occurred while \output is active []

LaTeX Warning: There were undefined references.

Package biblatex Warning: Please (re)run Biber on the file:
(biblatex)                main
(biblatex)                and rerun LaTeX afterwards.

Success!  Wrote 30 pages, 288102 bytes to main.pdf

```

**Comment by shiblon** [comment] 2020-12-11 13:10
Thank you! Found it. Let's try commit bc1162568c9b6843eabfe6043bb48f042401325e

Thanks for taking the time to try these out. Very helpful!

**Comment by shiblon** [comment] 2020-12-11 13:12
If you would like to post a bcf file (sanitized, if you desire) for me to use as a test, I can write one up that will ensure this continues working :)

**Comment by k4rtik** [comment] 2020-12-11 13:21
With the commit https://github.com/shiblon/latex-makefile/commit/bc1162568c9b6843eabfe6043bb48f042401325e the sed error goes away, but I still get the warning about undefined references and an empty (0-byte) `main.bbl`.

I am not sure what you mean by sanitized, but I posted one at https://gist.github.com/k4rtik/8af925f9ea25df7166351b217b8932d1

**Comment by shiblon** [comment] 2020-12-11 14:03
Thanks @k4rtik that's quite useful. I just put a test in there to ensure that parsing is happening properly. It looks like it is.

Now, as to the empty `main.bbl`, that's an interesting problem, and I think it's actually unrelated to this bcf change. It is possible that you need to delete `main.bbl` and try again - if it was already there from previous failed runs, that might trigger that particular error.

Sorry to go back and forth so much on this, but if you can try a clean make with the commit I posted, that might help. Barring that, try just building `main.d` and see what it contains. If it has the right "references.bib" line in it, then the bcf parser is working.

```
make main.d
```

would do that for you, without then deleting it afterward (as sometimes happens with make).

**Comment by k4rtik** [comment] 2020-12-11 14:20
Each time I am sharing any log, I make sure to `make clean` first and I just double-checked with the latest commit that it's not the old `main.bbl` lying around. It is still generated empty.

I do see the following at the very bottom of `main.d`:

```
.SECONDEXPANSION:
main.bbl main.aux main.aux.make: references.bib
```

**Comment by k4rtik** [comment] 2020-12-11 14:22
Oh, you may be right. I see that if I go back to my stable Makefile, even that is generating an empty .bbl file.

**Comment by k4rtik** [comment] 2020-12-11 14:29
I confirm that the changes in the `bcf` branch work fine on my linux machine. I do recall seeing this empty `.bbl` issue on macOS a week ago, so I concur that it is unrelated and hence, this issue can be considered resolved.

**Comment by k4rtik** [comment] 2020-12-11 14:44
I suspect my issue on macOS is some sort of file handle being left behind. I rebooted my machine and tested again and now it works fine.

Thanks so much for looking into and making these changes @shiblon. :)

**Comment by shiblon** [comment] 2020-12-11 16:06
My pleasure, and sorry it was so long between fixes. Back in the game now 👍 
Meanwhile, if you find something that can be better handled related to the bbl file issue, let's start a new bug (can reference this one).

Tagged with v2.2.1.

**Closed** 2020-12-11 16:06 UTC
Labels: Priority-Medium, Status-New, Type-Enhancement
